# Generated by Django 5.1.1 on 2024-10-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
